Cargo.lock, Cargo.toml, reckless_github/Cargo.toml, reckless_github/src/lib.rs, reckless_github/src/repository.rs, reckless_lib/src/repository.rs
This is for @swaptr to help in the repository design.
Feedbacks are welcome
=> feat(github): init github repository

Cargo.lock, reckless_cmd/src/reckless/config.rs, reckless_github/Cargo.toml, reckless_github/src/lib.rs, reckless_github/src/repository.rs, reckless_lib/Cargo.toml, reckless_lib/src/errors.rs, reckless_lib/src/lib.rs, reckless_lib/src/utils.rs
=> repo: define gh repository behavior

reckless_cmd/src/reckless/mod.rs, reckless_github/src/lib.rs, reckless_github/src/repository.rs, reckless_lib/src/lib.rs, reckless_lib/src/url.rs, reckless_lib/src/utils.rs
This PR adds support to abstract URL related functionalities to a separate struct.
=> lib: implement URL for easy url handling

reckless_github/src/lib.rs, reckless_lib/src/utils.rs
=> tests: delete residual test dirs

reckless_cmd/src/reckless/config.rs, storage/src/file.rs
This will fix some of bug for untested features
=> fix(cmd): fix bugs inside the directories path

coffee_lib/src/cln_conf.rs, coffee_lib/src/lib.rs
Fixes https://github.com/coffee-tools/coffee/issues/33
=> feat(lib): implement conf model for core lightning

coffee_cmd/src/coffee/cmd.rs, coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs, coffee_cmd/src/main.rs, coffee_github/src/repository.rs, coffee_lib/src/plugin.rs, coffee_lib/src/plugin_manager.rs
Fixes https://github.com/coffee-tools/coffee/issues/35
=> feat(cmd): semplify the install command

Cargo.lock, coffee_cmd/Cargo.toml, coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs, coffee_lib/src/errors.rs
=> feat(cmd): integrate the cln conf parser 

Cargo.lock, coffee_cmd/Cargo.toml, coffee_cmd/src/coffee/cmd.rs, coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs, coffee_cmd/src/main.rs, coffee_lib/src/plugin_manager.rs
support the setup command to link the core lightning config with the coffee managed config
=> feat(cmd): support the setup command

coffee_github/src/repository.rs
Currently, the code guesses the plugin language by iterating on each file. This PR makes coffee able to get language information from the coffee configuration file
Fixes #49
- New feature (non-breaking change which adds functionality)
- I forked `https://github.com/lightningd/plugins` and added coffee configuration file to the `probe` repo
- I commented out the code which iterates the files to guess the language
- - Then, I setup coffee from source using `cargo run -- remote add lightningd https://github.com/tareknaser360/plugins.git`.
- output: 
```
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
Running `target/debug/coffee_cmd remote add lightningd 'https://github.com/tareknaser360/plugins.git'`
```
- - Without the new code block, running `cargo run -- install probe` yielded …
=> Getting the plugin language from the coffee configuration file

coffee_cmd/src/coffee/mod.rs, coffee_github/src/repository.rs, coffee_lib/src/plugin.rs
This supports the possibility to install a plugin from the configuration file
=> fix: fix the process to read the config file

Cargo.lock, coffee_cmd/Cargo.toml, coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_lib/src/plugin_manager.rs, docs/docs-book/src/using-coffee.md
=> feat(core): add show command

Cargo.lock, Cargo.toml, README.md, coffee_plugin/Cargo.toml, coffee_plugin/src/main.rs, coffee_plugin/src/plugin.rs, coffee_plugin/src/plugin/plugin.rs, coffee_plugin/src/plugin/state.rs
This prepares the architecture for https://github.com/coffee-tools/coffee/issues/60
=> feat(plugin): add the generic interface to implement coffee as plugin 

coffee_lib/src/plugin.rs
=> fix(lib): fix typo inside the pip install script

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_lib/src/plugin_manager.rs, docs/docs-book/src/using-coffee.md
=> feat(core): add remote list command

coffee_core/src/coffee.rs, coffee_github/src/repository.rs, coffee_lib/src/cln_conf.rs, coffee_lib/src/plugin.rs
=> fix(git): fix derivation of the exec path 

Cargo.lock, coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/Cargo.toml, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, docs/docs-book/src/using-coffee.md
=> feat(core): add remove command

coffee_cmd/src/cmd.rs, coffee_cmd/src/coffee_term/command_show.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, docs/docs-book/src/using-coffee.md
=> fix(coffee): remove remotes flag from list command

coffee_core/src/coffee.rs
See https://github.com/coffee-tools/coffee/issues/128#issuecomment-1552318097 and commit for details
=> fix(core): allow dirty state for add remote

coffee_core/src/config.rs
=> fix(core): avoid double slash

.github/workflows/build.yml, .github/workflows/integration_testing.yml, Cargo.lock, Cargo.toml, Makefile, coffee_core/Cargo.toml, coffee_core/src/coffee.rs, coffee_lib/src/errors.rs, coffee_lib/src/macros.rs, coffee_lib/src/types/mod.rs, coffee_plugin/Cargo.toml, coffee_testing/Cargo.toml, coffee_testing/src/btc.rs, coffee_testing/src/cln.rs, coffee_testing/src/lib.rs, docker/Dockerfile, docker/docker-compose.yaml, docker/entrypoint.sh, tests/Cargo.toml, tests/src/coffee_integration_tests.rs, tests/src/lib.rs, tests/src/logger.rs
I need to add the docker image to work on the CI but this is good if @tareknaser360 want to run it locally
to run the tests it is possible to run `make integration` or `make integration ARGS="init_coffee_test_add_remote"` for a specific test
=> feat(tests): introducing tests framework

coffee_core/src/coffee.rs
This reverts commit 48dd734049d8e74373f29e6a98cd6a5055a3ef34.
Reverting the change made here https://github.com/coffee-tools/coffee/pull/149
=> Revert "fix(core): preserve user-defined network setting"

Cargo.lock, coffee_core/src/coffee.rs, coffee_testing/src/btc.rs, coffee_testing/src/cln.rs, tests/Cargo.toml, tests/src/coffee_integration_tests.rs
=> minors fixes in coffee core and trying to fix the CI tests failure regarding the integration tests

Cargo.lock
Trying to solve the CI issue with nightly due to some dependencies breakage
=> deps: update the dependencies to solve the nightly issue

Cargo.lock, coffee_core/src/coffee.rs, coffee_core/src/config.rs, coffee_lib/src/errors.rs, coffee_lib/src/utils.rs, coffee_storage/Cargo.toml, coffee_storage/src/file.rs, coffee_storage/src/lib.rs, coffee_storage/src/nosql_db.rs, coffee_storage/src/storage.rs
This adds more solid storage to coffee by using a no SQL database and using it to store the raw JSON.
However, there is a need to research if we need a more complex schema to make persistent the coffee information.
For now we keep it simple
=> feat(core): use the no sql database inside the coffee manager

Cargo.lock, coffee_testing/Cargo.toml, coffee_testing/src/lib.rs, tests/Cargo.toml, tests/src/coffee_integration_tests.rs
This PR adds a new test to replicate this error #145 
The test now fails but will come in handy to solve the issue
=> feat(test): add a new test to mimic cmd arguments

Cargo.lock, README.md, coffee_cmd/src/coffee_term/command_show.rs, coffee_core/Cargo.toml, coffee_core/src/coffee.rs, coffee_github/Cargo.toml, coffee_github/src/repository.rs, coffee_lib/src/macros.rs, coffee_lib/src/repository.rs, coffee_lib/src/types/mod.rs, coffee_storage/src/model/repository.rs
=> Modify `CoffeeRemoteList` to store the git HEAD 

.githooks/pre-commit, Makefile, docs/docs-book/src/contributing-to-coffee.md
=> feat: add fmt githook

README.md
Fixes loading issue for OSI logo.
=> fix: OSI logo loading

docker/Dockerfile
=> Install `grpcio-tools` in Docker Image
