coffee-tools/coffee

Cargo.lock, reckless_cmd/Cargo.toml, reckless_cmd/src/main.rs, reckless_cmd/src/reckless/cmd.rs, reckless_cmd/src/reckless/mod.rs, reckless_github/src/lib.rs, reckless_lib/src/plugin_manager.rs
This is my work to add an API for the cmd in order to support the feature added by this PR https://github.com/cln-reckless/reckless.rs/pull/4
I think that the remote need an additional sub command
=> feat(cmd): add possibility to add a remote repository

Cargo.lock, reckless_cmd/Cargo.toml, reckless_cmd/src/main.rs, reckless_cmd/src/reckless/mod.rs, reckless_github/Cargo.toml, reckless_github/src/lib.rs, reckless_github/src/repository.rs, reckless_lib/Cargo.toml, reckless_lib/src/errors.rs, reckless_lib/src/utils.rs
This PR will add logging support for reckless!
Fixes #5 
```bash
Running `target/debug/reckless_cmd remote add plugins 'https://github.com/lightningd/plugins'`
[2022-11-19T14:37:29Z DEBUG reckless_cmd::reckless] REMOTE ADDING: plugins https://github.com/lightningd/plugins
[2022-11-19T14:37:29Z DEBUG reckless_github::repository] ADDING REPOSITORY: plugins https://github.com/lightningd/plugins
[2022-11-19T14:37:29Z DEBUG reckless_github::repository] INITIALIZING REPOSITORY: plugins https://github.com/lightningd/plugins > /home/swapnil/.reckless/lightningd/plugins
[2022-11-19T14:37:30Z DEBUG reckless_lib::utils] SUBMODULE COUNT: 14
[2022-11-19T14:37:30Z DEBUG reckless_lib::utils] URL 1: https://github.com/clightning4j/btcli4j.git
[2022-11-19T14:37:32Z DEBUG reckless_lib::utils] ADDED …
```
=> log: add logging

reckless_lib/src/plugin.rs
This allows storing information inside a plugin regarding the languages.
I'm still not sure how to get the default install information, maybe from a file or maybe just hardcoded. Not sure, but for now I think it is a good design of how to configure the process looks like!
=> feat(lib): define the default install process for the plugin

reckless_cmd/src/reckless/mod.rs, reckless_github/src/lib.rs, reckless_lib/src/url.rs
This PR allows cloning remote repo into user defined paths.
Earlier, adding remote repo would result in paths such as `{HOME}/.reckless/repositories/username/repo` which would disregard the `name` argument provided by the user.
Now, adding remote repo would result in path `{HOME}/.reckless/repositories/name/`.
=> url: move remote repo to user defined dir

Cargo.lock, reckless_cmd/Cargo.toml, reckless_cmd/src/main.rs, reckless_cmd/src/reckless/cmd.rs, reckless_cmd/src/reckless/mod.rs, reckless_github/Cargo.toml, reckless_github/src/repository.rs, reckless_lib/Cargo.toml, reckless_lib/src/plugin.rs, reckless_lib/src/plugin_conf.rs, reckless_lib/src/plugin_manager.rs, reckless_lib/src/repository.rs
This PR is a clean-up of the
https://github.com/cln-reckless/reckless.rs/pull/14
that clean up the install script and configure and
fix without breaking the architecture of the plugin manager
the `Send` and `Sync` tokio requirements.
=> feat(reckless): support install command 

reckless_cmd/src/reckless/config.rs, reckless_cmd/src/reckless/mod.rs, reckless_github/src/lib.rs, reckless_lib/src/url.rs, reckless_lib/src/utils.rs
This will enable the reckless configuration, and also enable us to keep track of the plugin path that are installed
=> feat: start to support the plugin manager configuration

Cargo.lock, Cargo.toml, reckless_cmd/Cargo.toml, reckless_cmd/src/reckless/cmd.rs, reckless_cmd/src/reckless/mod.rs, storage/Cargo.toml, storage/src/file.rs, storage/src/lib.rs, storage/src/storage.rs
This introduces a storage crate that allows implementing a storage manager that allows implementing the kind of storage that can store the plugin manager information on the disk.
=> feat(storage): add a storage crate

reckless_github/Cargo.toml, reckless_github/src/repository.rs, reckless_lib/src/plugin.rs
This will write in a known bug-free plugin identification because the previous implementation was a little bit messy and untested.
Each time that a language was found will create a new plugin, this is wrong because it is just a guess that we can do this way, and we can risk trying to be smart but we are really dumb like in the case of javascript that it can contains also the typescript configuration and in this case, we do not know what happens.
The work is not finished because the configuration should override the guess about the language, because the conf information is more important for the plugin manager.
=> fix(github): fix the plugin identification

Cargo.lock, coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs, coffee_cmd/src/main.rs, coffee_github/Cargo.toml, coffee_github/src/repository.rs, coffee_lib/src/plugin.rs, coffee_lib/src/repository.rs, coffee_lib/src/url.rs, storage/Cargo.toml, storage/src/file.rs, storage/src/lib.rs, storage/src/model.rs, storage/src/model/repository.rs, storage/src/storage.rs
This is a working-in-progress PR that allows making a file persistence of the plugin manager status.
It is a monkey solution but good enough to unlock some of our blocking tasks
Fixes https://github.com/cln-reckless/coffee/issues/20
=> feat(storage): implement file storage

coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs, coffee_github/src/repository.rs, coffee_lib/src/cln_conf.rs, coffee_lib/src/plugin.rs, coffee_lib/src/utils.rs, coffee_storage/src/file.rs
This fixes a couple of bugs and adds the support to create the core lightning configuration, now the step missed is loading the configuration and link it to core lightning
=> feat: add possibility to create the configuration

coffee_cmd/src/coffee/cmd.rs, coffee_cmd/src/coffee/mod.rs, coffee_cmd/src/main.rs, coffee_lib/src/plugin.rs, coffee_lib/src/plugin_manager.rs
In the main.rs file, 
Running the install command without the --verbose flag, produces this ouput:
{Note: the file is already present on my local system that's why it is showing the error}
```
$ cargo run -- install rebalance 
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/coffee_cmd install rebalance`
[2023-02-28T08:05:21Z ERROR coffee_lib::errors] ERROR #1: field plugin with value /home/harshit/.coffee/repositories/lightningd/rebalance/rebalance.py already present
thread 'main' panicked at 'code: 1, msg: field plugin with value /home/harshit/.coffee/repositories/lightningd/rebalance/rebalance.py already present', coffee_cmd/src/main.rs:42:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Running the install command with …
=> feat: Support the verbose output while running the install and upgrade command

coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs, coffee_github/src/repository.rs, coffee_lib/src/plugin.rs
Fix to avoid overriding the language when it is found.
When we found what we are looking for we return and stop to search.
Fixes 4016ce84
Introduced in https://github.com/coffee-tools/coffee/pull/50
cc @tareknaser360
=> fix: avoid to override the language when found

coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs
Instead of just storing the plugin path as a string in a vector, we store the plugin information as a vector of Plugins.
The struct Plugin contains:
- `name` The name of the plugin
- `path` The path of the plugin
- `lang` The language of the plugin
- `conf` The configuration of the plugin
This paves the way for implementing the `list` function. We can then simply iterate over `plugins` vector and get the information we want and format the output as needed.
Fixes #53 
Please delete options that are not relevant.
- This builds normally on my machine 
- I ran `make` locally before pushing this code 
**Test Configuration**:
- Firmware version: Ubuntu 20.04.5 LTS
- Running Bitcoin Core Signet
- Running Core Lightning using btcli4j plugin
=> Store installed plugins as a vector of plugin struct

coffee_cmd/src/coffee/mod.rs
This option is already implemented in CLNConf Parser.
`pub(crate) fn new(file_path: &str, create_if_missing: bool)`
I just set `create_if_missing` to be true.
Fixes #57
=> Create core lightning config file if missing

Cargo.lock, coffee_cmd/Cargo.toml, coffee_cmd/src/coffee/cmd.rs, coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs, coffee_cmd/src/main.rs, coffee_lib/src/plugin_manager.rs
Fixes https://github.com/coffee-tools/coffee/issues/66
Fixes https://github.com/coffee-tools/coffee/issues/36
this PR allow to add a plugin dynamically and skipping the configuration file
```
RUST_LOG=info cargo run -- --network testnet setup /run/media/vincent/VincentSSD/.lightning
RUST_LOG=info cargo run -- --network testnet install summary --verbose --dynamic
```
Please note that now the setup take the core lightning root directory
=> allow to run the plugin in a dynamic way 

Cargo.lock, coffee_cmd/Cargo.toml, coffee_cmd/src/coffee/cmd.rs, coffee_cmd/src/coffee/config.rs, coffee_cmd/src/coffee/mod.rs
Fixes https://github.com/coffee-tools/coffee/issues/68
Now the command accept also `--data-dir=/tmp`
an example of command is
```
RUST_LOG=info cargo run -- --network testnet --data-dir=/tmp install summary --dynamic
```
=> feat: allow to run the plugin in a dynamic way

Cargo.lock, coffee_cmd/src/coffee/cmd.rs, coffee_cmd/src/coffee/mod.rs, coffee_cmd/src/main.rs, coffee_github/src/repository.rs, coffee_lib/Cargo.toml, coffee_lib/src/plugin_manager.rs, coffee_lib/src/repository.rs
- Running `cargo run -- list` shows all the plugin that is installed by coffee in JSON format
- Running `cargo run -- list --remotes` shows all the plugin that available to install from the added remote repositories 
Fixes #42
=> Adding support for `list` command

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_lib/src/plugin_manager.rs, docs/docs-book/src/using-coffee.md
running `cargo run -- remote remove <repo name>` will: 
- remove the directory from local storage
- update the JSON file with the dump of coffee status
This is related to #13
=> feat(core): add remove remote command

docs/docs-book/src/introduction.md
The current installation command for btcli4j on the testnet network is incorrect and does not work as expected. This commit updates the command to use 'coffee --network testnet install btcli4j' which installs the package correctly.
=> fix: Update installation command for btcli4j

Cargo.lock, Cargo.toml, Makefile, README.md, coffee_httpd/Cargo.toml, coffee_httpd/src/cmd.rs, coffee_httpd/src/httpd.rs, coffee_httpd/src/httpd/server.rs, coffee_httpd/src/main.rs
This can be tested as
```
RUST_LOG=debug cargo run --bin coffee_httpd --  --help
RUST_LOG=debug cargo run --bin coffee_httpd -- --network testnet
```
and by default, the server will be running on `localhost:8080` where there is a Swagger UI to see what kind of API are provided.
=> feat(httpd): init the http deamon

coffee_cmd/src/coffee_term.rs, coffee_cmd/src/coffee_term/command_show.rs, coffee_cmd/src/main.rs, coffee_cmd/src/term.rs, coffee_cmd/src/term/command_show.rs, coffee_core/src/coffee.rs, coffee_lib/src/lib.rs, coffee_lib/src/plugin.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs
radicle_term is pretty good to build a couple of UI component in the terminal,
for example the `coffee list --remotes` has the following result on my system
```
➜  coffee git:(macros/termianl-ui) cargo run --bin coffee -- --network testnet remote list
Finished dev [unoptimized + debuginfo] target(s) in 0.18s
Running `target/debug/coffee --network testnet remote list`
● List of repositories
╭─────────────────────────────────────────────────────────────────────────────╮
│ ●   Repository Alias   URL                                       N. Plugins │
├─────────────────────────────────────────────────────────────────────────────┤
│ ●   folgore-git        https://github.com/coffee-tools/folgore   1          │
│ ●   lightningd         https://github.com/lightningd/plugins     27         │
│ ● …
```
=> feat(cmd): use the radicle_term to build a nice TUI

coffee_github/src/repository.rs
when we read from config of the plugin we should
build the path with `{root_path}/{main}` and not
the `{root}/{name}`.
=> fix(cmd): fix the path derived from the config file

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, docs/docs-book/src/using-coffee.md
- added a hashset of the remote repositories names to the storage information of coffee on disk (JSON)
- added a function to check if the remote repository clone was deleted from disk manually and called it when needed
=> fix(coffee): don't allow duplicate repositories 

coffee_lib/src/plugin.rs
This commit fix the install the poetry plugin by fixing the command string, with the previous on there was some parsing issue.
Reported-by: @dcrystalj
Link: https://github.com/coffee-tools/coffee/issues/138
=> fix(lib): fix the install string for poetry install

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_github/src/repository.rs, coffee_github/src/utils.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/repository.rs, coffee_lib/src/types/mod.rs, coffee_storage/src/model/repository.rs, docs/docs-book/src/using-coffee.md
Fixes #43 
-  The code implements the `upgrade` command
- Users can choose to upgrade a single repository or all repositories
- To upgrade a single repository, the user runs `coffee upgrade <repo_name>`
- To upgrade all repositories, the user runs `coffee upgrade --all`
- It is not possible to use the `all` flag with a specific repository name
- The `upgrade` function returns a `CoffeeUpgrade` object indicating whether the local clone is up to date or not
- A new field called `branch` has been added to the repository structure
- This field accounts for the situation where the main branch is referred to as `master`
- The `branch` field will facilitate future work on issue #131.
=> feat(coffee): implement upgrade command

Cargo.lock, coffee_httpd/Cargo.toml, coffee_httpd/src/httpd/server.rs
- Added a new function coffee_list to handle the `/list` endpoint.
- The function takes the data parameter of type `web::Data<AppState>` to access the shared state.
- The function doesn't take any body
This is the response from the server for this call
=> feat(httpd): implement list call

coffee_httpd/src/httpd/server.rs
This pull request adds three new endpoints:
-  `coffee_remote_add`  This endpoint handles the addition of a remote repository. It expects a POST request with a JSON body containing the `repository_name` and `repository_url` parameters. 
- `coffee_remote_rm`  This endpoint handles the removal of a remote repository. It expects a POST request with a JSON body containing the `repository_name` parameter. 
- `coffee_remote_list` This endpoint handles the retrieval of the list of remote repositories. It expects a GET request and returns a JSON object.
To test the new endpoints: 
- 
-
```
curl -X 'POST' \
'http://localhost:8080/remote/add' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"repository_name": "Folgore",
"repository_url": …
```
=> feat(httpd): implement remote endpoint

coffee_lib/src/macros.rs
We was usul to return Ok when a command fails because we was ignoring the command result.
With this commit now we are able to report the error to the user.
Fixes https://github.com/coffee-tools/coffee/issues/146
=> fix(lib): report the error when the command fails

coffee_core/src/coffee.rs
Addresses #145 
Coffee does not consider the network parameter when setting up the configuration. 
Currently, the configuration is being overwritten with the stored configuration, which prevents users from setting the desired network. 
By removing the line that overwrites the configuration in the inventory function, the user will be able to explicitly set the network parameter.
=> Refactor configuration handling to preserve user-defined setting

coffee_core/src/coffee.rs, coffee_core/src/config.rs
Fixes #151
So this is a double solution to make sure the issue is solved.
1- we create the `repositories` folder beforehand along with the `bitcoin` and `testnet` folders. 
- This by itself should solve the issue.
2- we provide a proper error message to the user if the folder is missing.
=> fix(core): create repositories folder when configuring coffee

coffee_lib/src/plugin.rs
Python decided after many years to tell the user that installing the dependencies with pip without a virtual environment is a bad idea
So now we should try a solution to handle these cases
```
➜  coffee git:(macros/sh-report-failure) ✗ coffee --network testnet install helpme
[2023-06-20T10:20:03Z ERROR coffee_lib::errors] ERROR #2: error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
python-xyz', where xyz is the package you are trying to
install.
If you wish to install a non-Arch-packaged Python package,
create a virtual environment using 'python -m venv path/to/venv'.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.
If you wish to install a non-Arch packaged Python application,
it may be …
```
=> fix(lib): Fix pip braking change that required --break-system-packages

Cargo.lock, coffee_testing/Cargo.toml, coffee_testing/src/lib.rs, tests/src/coffee_integration_tests.rs
This commit revert my previous solution to clone the tmpdir, because it is wrong, the tmpdir wil be deleted when the first instance is dropped.
So this commit use the Arc to pass around the tmp dir, so in this way we keep a smart pointer and we solve all our problem.
=> fix(test): use the tmpdir in the correct way

tests/src/coffee_plugin_integration_tests.rs
This commit just increate the timeout for plugin integration testing.
=> fix(test): increase the timeout for the plugin integration testing

coffee_testing/src/cln.rs, tests/src/coffee_plugin_integration_tests.rs
Inside the CI we noted that the tests over the plugin get stuck and my suspection is that we had some problem to run the plugin with the `lightning-cli plugin start`.
So this is removing the method to start it when cln will start, and running it with the deamon itself.
=> fix(test): run core lightning with the plugin directly

Cargo.lock, coffee_cmd/src/coffee_term/command_show.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_github/src/repository.rs, coffee_github/src/utils.rs, coffee_httpd/Cargo.toml, coffee_httpd/src/cmd.rs, coffee_httpd/src/httpd.rs, coffee_httpd/src/httpd/macros.rs, coffee_httpd/src/httpd/server.rs, coffee_httpd/src/main.rs, coffee_lib/Cargo.toml, coffee_lib/src/macros.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/repository.rs, coffee_lib/src/types/mod.rs, coffee_testing/src/lib.rs, docs/docs-book/src/using-coffee.md, tests/Cargo.toml, tests/src/coffee_httpd_integration_tests.rs
This pull request adds two new endpoints:
-  `coffee_install`  
- `coffee_remove` 
To test the new endpoints: 
- 
-
```
curl -X 'POST' \
'http://localhost:8080/install' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"plugin": "summary"
}' 
```
- 
```
curl -X 'POST' \
'http://localhost:8080/remove' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"plugin": "summary"
}' 
```
=> feat(httpd): implement install and remove enpoints

coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, coffee_testing/src/btc.rs, coffee_testing/src/cln.rs, docs/docs-book/src/using-coffee.md, tests/src/coffee_httpd_integration_tests.rs, tests/src/coffee_integration_tests.rs, tests/src/coffee_plugin_integration_tests.rs
e51181172ba221ed944917b1d0eb57aac82022fd modifies the current test framework to allow to run a lightning node in any network specified in the test itself. 
-  previously we could only run lightning in `regtest`
49548f0c247b19491aa56fcf41eba826bc14922f adds a new test to mimic the issue where coffee fails to install the same plugin in 2 different networks.
Related issue: #172
=> Deprecate the nurse command and add a test

coffee_core/src/coffee.rs, coffee_github/src/repository.rs, coffee_lib/src/url.rs, coffee_storage/src/file.rs, coffee_storage/src/model/repository.rs, coffee_storage/src/nosql_db.rs, coffee_storage/src/storage.rs, coffee_testing/src/btc.rs, coffee_testing/src/cln.rs, coffee_testing/src/lib.rs, tests/src/coffee_integration_tests.rs
While working with coffee, we noted that there was a
limitation on how we store the repositories.
In fact, we store them once per network, and this causes problem
when we try to work with multiple networks,
and installing the same plugins.
Now with this commit, we store the repositories globally,
outside of the configuration network, so in this way we
can download once the remote is on and use
it in multiple directories.
Fixes https://github.com/coffee-tools/coffee/issues/172
=> fix(core): store the repository globally

coffee_core/src/coffee.rs, tests/src/coffee_integration_tests.rs
- handles the `Err` variant in 2 statements in coffee.rs
- suppresses 2 clippy warnings that are intended 
- removes redundant `root_path` from `install_plugin_in_two_networks` test
=> supress intended clippy warnings 

README.md, coffee_httpd/src/httpd/macros.rs, coffee_httpd/src/httpd/server.rs, coffee_lib/src/types/mod.rs, coffee_testing/src/lib.rs, tests/src/coffee_httpd_integration_tests.rs
- fixes the links to crates in the `README` file
- define a new type Show to send to the show http endpoint
- implement coffee_show function to handle /show endpoint
- add an httpd integration test to further stress test the server.
See commit body for details
=> Implement the `show` endpoint in the httpd crate

coffee_lib/src/types/mod.rs
If you are installing coffee with make install you will receive the following error
```
Compiling git2 v0.16.1
Compiling coffee_lib v0.1.0 (/home/vincent/Github/coffee/coffee/coffee_lib)
error[E0433]: failed to resolve: use of undeclared crate or module `paperclip`
--> coffee_lib/src/types/mod.rs:5:9
|
5 |     use paperclip::actix::Apiv2Schema;
|         ^^^^^^^^^ use of undeclared crate or module `paperclip`
error: cannot determine resolution for the derive macro `Apiv2Schema`
--> coffee_lib/src/types/mod.rs:8:34
|
8 |     #[derive(Debug, Deserialize, Apiv2Schema, Serialize)]
|                                  ^^^^^^^^^^^
|
= note: import resolution is stuck, try simplifying macro imports
error: cannot determine resolution for the derive macro `Apiv2Schema`
--> …
```
=> fix(lib): fixing the feature confitional compilation

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_httpd/src/httpd/server.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, docs/docs-book/src/using-coffee.md, tests/src/coffee_httpd_integration_tests.rs, tests/src/coffee_integration_tests.rs
=> feat(core): add search command

coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_core/src/nurse.rs, coffee_core/src/nurse/chain.rs, coffee_core/src/nurse/strategy.rs
Please review each commit by review also the comments of the module.
=> Redesign of the nurse command

tests/src/coffee_integration_tests.rs
=> Validate There is no Double Slash in `root_path` or `exec_path`

coffee_cmd/src/coffee_term/command_show.rs, coffee_core/src/coffee.rs
prints the first 7 characters of the commit HEAD instead of the entire commit hash
fixes #192
=> feat(cmd): print the short version of git HEAD

coffee_lib/src/macros.rs
working on https://github.com/coffee-tools/coffee/issues/194 I noticed a issue with the `sh` macro when trying to execute a script that uses a pipe. Looking into the implementation I saw that it tries to manually parse out the commands, which is pretty error prone. so, instead of trying to manually parse the script and potentially making errors, let the actual `sh` command do the work correctly
=> fix(lib): simplify and improve sh! macro

coffee_testing/src/cln.rs, docker/Dockerfile
This is being added instead of the build-time setting for v23.11.
=> ci: update to the last cln version on master

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_httpd/src/httpd/server.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, docs/docs-book/src/using-coffee.md, tests/src/coffee_httpd_integration_tests.rs, tests/src/coffee_integration_tests.rs
This pull request introduces a new command to `coffee`, allowing users to list plugins in a remote repository.
To list plugins in a remote repository, simply run:
```bash
coffee remote <repository_name> --plugins
```
=> Add Command to List Plugins in a Remote Repository

coffee_lib/src/types/mod.rs, tests/src/coffee_httpd_integration_tests.rs
- This PR enhances the testing structure in `coffee_httpd` by breaking down the test into two.
- All `http` endpoints are tested 
- In the `httpd_add_remove_plugins` test, we test endpoints like `/remote/add`, `/install`, `/remote/list`, `/list`, `/remove`, and `/remote/rm`
- In `httpd_search_list_plugins`, we test (`/remote/list_plugins`, `/show`, `/search`)
- Additionally, this PR eliminates redundant `request` type definitions found in `coffee_lib/src/types/mod.rs`
Related issue: #202
Fixes https://github.com/coffee-tools/coffee/issues/202
=> Enhance `coffee_httpd` Test Structure and Remove Redundant Type Definitions

coffee_cmd/src/cmd.rs, coffee_cmd/src/coffee_term/command_show.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/config.rs, coffee_core/src/lib.rs, coffee_httpd/src/cmd.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, coffee_plugin/src/plugin/state.rs, coffee_testing/src/lib.rs, docs/docs-book/src/using-coffee.md, tests/src/coffee_integration_tests.rs
This pull request introduces enhancements to `coffee` command-line tool:
- `coffee` now checks the status of its configuration before executing each command.
- If the configuration is found to be in an unsatisfactory state, the command will return an error.
- To bypass this verification step, users can employ the `--skip-verify` flag.
- Implemented `is_sane` for `CoffeeNurse` type to assess the sanity of the `coffee` configuration.
- Introduced the `organize` method for `CoffeeNurse`, ensuring each action is included only once.
- Added a new method, `coffee_verify`, which allows users to check `coffee` configuration's status without taking any action.
- The `coffee nurse` command now supports a `--verify` flag, which invokes the `coffee_verify` method.
- Included a test case for the …
=> Improved Coffee Verification and CoffeeNurse Functionality

coffee_httpd/Cargo.toml
- Added the `Derive` feature to clap in `coffee_httpd/Cargo.toml`
This pull request resolves an issue where the `coffee_httpd` crate was unable to compile on its own. The changes specifically adds the `Derive` feature to clap in the `coffee_httpd/Cargo.toml` file.
Here is a related discussion https://github.com/rust-lang/cargo/issues/11551 
Fixes #215
=> Add `Derive` Feature to `Clap` in `coffee_httpd` `Cargo.toml`

docs/docs-book/src/install-coffee.md, docs/docs-book/src/using-coffee.md
The link was previously showing 404 error, fixed it. Also, a minor typo in the docs.
=> fix: typo and docs link

coffee_core/src/coffee.rs
Sometimes we may do operations like delete a directory that is linked with coffee, but we forget it.
So this code makes sure that we are operating on a piece of safe information.
Fixes https://github.com/coffee-tools/coffee/issues/209
Alternative to https://github.com/coffee-tools/coffee/pull/211 this should fix the real problem
=> fix(cmd): check if the ln path that we know are good

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_lib/src/plugin.rs, coffee_lib/src/plugin_manager.rs
Created a draft PR for adding verbose flag support to upgrade command.
Issue Reference- https://github.com/coffee-tools/coffee/issues/214
=> feat: add verbose flag to upgrade

Cargo.lock, coffee_cmd/src/coffee_term/command_show.rs, coffee_cmd/src/main.rs, coffee_core/Cargo.toml, coffee_core/src/coffee.rs, coffee_github/Cargo.toml, coffee_github/src/repository.rs, coffee_github/src/utils.rs, coffee_lib/Cargo.toml, coffee_lib/src/macros.rs, coffee_lib/src/plugin.rs, coffee_lib/src/repository.rs, coffee_lib/src/types/mod.rs
I was on a plane and I found the time to write a PoC for better upgrade commands, this also introduced a simplification of the code
Fixes https://github.com/coffee-tools/coffee/issues/223
Fixes https://github.com/coffee-tools/coffee/issues/214
=> coffee: fix the upgrade commands

coffee_cmd/src/main.rs
Fixes https://github.com/coffee-tools/coffee/issues/118
=> cmd: improve the error formatting

CONTRIBUTING.md, README.md
=> Move `CONTRIBUTING.md` File to Project Home

coffee_core/src/coffee.rs
Revise the plugin upgrade logic to only perform upgrades to plugins if the repository was updated. This prevents unnecessary plugin upgrades.
=> Only Upgrade Plugins if Needed

Cargo.lock, coffee_storage/src/nosql_db.rs
Fixes the following error
[2024-02-07T11:12:37Z ERROR sled::config] cache capacity is limited to the cgroup memory limit: 964485120 bytes
=> feat: use low level API to configure the API

coffee_cmd/src/cmd.rs, coffee_cmd/src/coffee_term/command_show.rs, coffee_cmd/src/main.rs, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_github/src/repository.rs, coffee_httpd/src/httpd/server.rs, coffee_lib/src/plugin.rs, coffee_lib/src/plugin_manager.rs, coffee_lib/src/types/mod.rs, docs/docs-book/src/using-coffee.md
This PR adds support for `coffee disable` and `coffee enable` commands, allowing users to toggle plugin status without complete uninstallation. 
The implementation ensures backward compatibility by making the new field "enabled" optional in the plugin struct.
Closes #102
- Implemented `disable` and `enable` methods for `CoffeeManager`
- Added CLI commands `coffee enable/disable <plugin_name>`
- Included HTTP endpoints for the new commands
- Updated documentation
- Integration testing for both `coffee` and `coffee_httpd`, to be added following #236
- Add `coffee disable --all` to disable all plugins with a single command
=> Add `coffee disable` and `coffee enable` Commands

coffee_core/src/coffee.rs
If you call coffee install more than once it will create folders like this:
1. ~/.coffee/<network>/plugins/<plugin_name>
2. ~/.coffee/<network>/plugins/<plugin_name>/<plugin_name>
the -T option for cp should fix this.
=> install command: add -T option to cp to not create nested folders on duplicate calls

coffee_cmd/src/main.rs
When running `coffee install` and there is an error e.g. the plugin could not be started by cln, coffee does not print an error. Not even in `verbose` mode. Only with the `RUST_LOG` env you can eventually see what happens. I propose to always show an install error to the user who just follows the documentation.
=> Always print install errors

coffee_core/src/coffee.rs, coffee_lib/src/types/mod.rs
When fetching an invoice with an amount and then paying that invoice cln will error if you've sent an amount on the pay command aswell.
Tip also expected an incompatible `CoffeeTip` response from `pay`. `pay` responses don't have a field `for_plugin` or `invoice`
tested with cln 24.02rc2
=> fix: tip function sent unwanted amount and expected wrong response

coffee_core/src/coffee.rs
- dynamic plugins now get saved persistently
- on remove dynamic plugins get stopped
- do not return on every Err, if it's expected
part of #245
=> feat(core): consistent dynamic plugins install/remove

coffee_core/src/coffee.rs
Potential fixes https://github.com/coffee-tools/coffee/issues/246
also @tareknaser noted that the commit https://github.com/coffee-tools/coffee/commit/eb4f6d29efcb7e715e8339b706e7219fec54cfa2 does not make sense because we will never duplicate directory
This was caused by the plugin duplication bug
=> fix: do not allow install duplicated plugin

coffee_core/src/coffee.rs, coffee_lib/src/plugin.rs, coffee_lib/src/plugin_conf.rs, docs/docs-book/src/support-coffee.md
added a new manifest field to mark plugin as important and only install it as static and important
part of #245
=> feat: support important plugins

coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/src/lib.rs, docs/docs-book/src/using-coffee.md
This commit changes the CLI command to get available plugins in a remote repository in coffee. 
Previously the user had to run `coffee remote <repository_name> --plugins` which was confusing. This commit changes it to be `coffee remote inspect <repository_name>` and updates documentation.
Fixes #261
=> Rename Command to Get Available Plugins in a Remote

coffee_cmd/src/cmd.rs
This PR validates the argument passed into the `-n` flag, and ensures only supported CLN networks are created in the `/Users/User/.coffee` directory, and closes #270 .
The current implementation consists of:
- An enum (`ClnNetwork`) with `Mainnet`, `Testnet`, `Signet`, and `Regtest` as variants
- A `ClnNetwork` implementation (`impl`) with a `from_str` function that `match`es on the `network` (`&str`) argument and returns a `ClnNetwork` variant, and  `to_str` function that `match`es on the `ClnNetwork` variant and returns the network `String`.
- The `network` function validates the `-n` argument.
The validation works as expected, so passing in a random name as the network name will not create the directory but the command returns the same output as below regardless of the network name. …
=> fix(cmd): add network validation in coffee cmd inputs

coffee_cmd/src/cmd.rs
This PR addresses @vincenzopalazzo comment [here](https://github.com/coffee-tools/coffee/pull/274#discussion_r1596915003) to follow the import rule on the codebase.
=> chore(cmd): organize imports properly

coffee_cmd/src/coffee_term/command_show.rs
This PR addresses @tareknaser and @vincenzopalazzo suggestion in [#239 (comment](https://github.com/coffee-tools/coffee/pull/239#discussion_r1563209333))
Closes #268
=> chore(cmd): change table label 

Cargo.lock, coffee_cmd/Cargo.toml, coffee_cmd/src/cmd.rs, coffee_cmd/src/main.rs, coffee_core/Cargo.toml, coffee_core/src/coffee.rs, coffee_core/src/lib.rs, coffee_github/Cargo.toml, coffee_httpd/Cargo.toml, coffee_httpd/src/main.rs, coffee_lib/Cargo.toml, coffee_lib/src/plugin_manager.rs, coffee_plugin/src/plugin/plugin_mod.rs, coffee_plugin/src/plugin/state.rs, docs/docs-book/src/introduction.md, docs/docs-book/src/using-coffee.md, tests/src/coffee_integration_tests.rs
This pull request adds the `coffee unlink` command and renames the `coffee setup` command to `coffee link`.
Fixes #278
- **Rename `setup` Command to `link`**
- Change function names from `setup_*` to `link_*` (e.g., `setup_with_cln` to `link_with_cln`)
- Update command references in `httpd` and `plugin` crates
- Update documentation 
- **Add `coffee unlink` Command**
- Add methods in `coffee_core` to enable unlinking coffee configuration from CLN configuration
- Update `coffee_cmd` crate to include the new `unlink` command
- Add documentation for the `unlink` command
_Note: The commits are organized so that the renaming of `coffee setup` is in one commit, and the addition of `coffee unlink` is in a separate commit. The `clightningrpc-conf` from git is required to use the `rm_subconf()` …
=> Add `coffee unlink` Command 
